networks:
  edrive:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - edrive
    ports:
      - 6379:6379
  
  manager:
    build:
      context: ./manager
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
    networks:
      - edrive
    depends_on:
      - redis
    ports:
      - 33007:33007

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
    networks:
      - edrive
    ports:
      - 5000:5000
    depends_on:
      - redis
      - manager

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      - MANAGER_HOST=manager
      - REDIS_HOST=redis
    networks:
      - edrive
    depends_on:
      - manager
    deploy:
      replicas: 3
